<?php
require 'vendor/autoload.php';

use Dompdf\Dompdf;

include "config/db.php";

/* KPI DATA */
$total_students = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM students"))['total'];
$total_companies = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM companies"))['total'];
$total_applications = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM applications"))['total'];
$pending = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM applications WHERE status='Pending'"))['total'];
$accepted = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM applications WHERE status='Accepted'"))['total'];
$rejected = mysqli_fetch_assoc(mysqli_query($conn,"SELECT COUNT(*) as total FROM applications WHERE status='Rejected'"))['total'];

/* HTML */
$html = '
<!DOCTYPE html>
<html>
<head>
<style>

body {
    font-family: Arial, sans-serif;
    padding: 20px;
    color: #333;
}

.header {
    text-align: center;
    border-bottom: 2px solid #333;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

.header h1 {
    margin: 0;
}

.header p {
    margin: 5px 0;
    font-size: 12px;
}

.grid {
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    margin-top: 20px;
}

.card {
    width: 45%;
    padding: 15px;
    border-radius: 10px;
    background: #f5f5f5;
    margin-bottom: 15px;
}

.card h3 {
    margin: 0;
    font-size: 14px;
}

.card h2 {
    margin: 5px 0 0 0;
    font-size: 22px;
}

.blue { border-left: 5px solid #3b82f6; }
.green { border-left: 5px solid #22c55e; }
.orange { border-left: 5px solid #f59e0b; }
.red { border-left: 5px solid #ef4444; }

.footer {
    position: fixed;
    bottom: 0;
    text-align: center;
    font-size: 10px;
    width: 100%;
    border-top: 1px solid #ccc;
    padding-top: 5px;
}

</style>
</head>

<body>

<div class="header">
    <h1>InternTrack Pro</h1>
    <p>Reports Dashboard Official Summary</p>
</div>

<div class="grid">

    <div class="card blue">
        <h3>Total Students</h3>
        <h2>'.$total_students.'</h2>
    </div>

    <div class="card green">
        <h3>Total Companies</h3>
        <h2>'.$total_companies.'</h2>
    </div>

    <div class="card orange">
        <h3>Total Applications</h3>
        <h2>'.$total_applications.'</h2>
    </div>

    <div class="card red">
        <h3>Pending Applications</h3>
        <h2>'.$pending.'</h2>
    </div>

    <div class="card">
        <h3>Accepted</h3>
        <h2>'.$accepted.'</h2>
    </div>

    <div class="card">
        <h3>Rejected</h3>
        <h2>'.$rejected.'</h2>
    </div>

</div>

<div class="footer">
    Generated by InternTrack Pro System
</div>

</body>
</html>
';

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$dompdf->stream("interntrack-report.pdf", [
    "Attachment" => false
]);
exit;